--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
INSERT INTO Clients(name,surname,phone_number,registration_date,status,gender)
VALUES('Piotr', 'NOWY', '834376543', GETDATE(), 'aktywny', 'M')
COMMIT;